### ISSUE TITLE
N-API: tracing work items for stage 1

### ISSUE THREAD

**Issue by yorkie** [Rokid/ShadowNode#231]
The following APIs are behind this track:

- [x] Version Management (#267)
- [x] Error Handling (#260, #281, #302)
- [x] Object Lifetime management (#268, #277, #298, #304)
- [x] Module register (#243)
- [x] Working with JavaScript Values (#260, #270, #296, #297)
- [x] Working with JavaScript Values - Abstract Operations (#270, #281, #297)
- [x] Working with JavaScript Properties (#260, #264)
- [x] Working with JavaScript Functions (#260, #273, #277, #295)
- [x] ObjectWrap (#277)

**Comment by legendecas** [comment]
## Error Handling

### Return values

- [ ] napi_get_last_error_info

### Exceptions

- [ ] napi_throw
- [ ] napi_throw_error
- [ ] napi_throw_type_error
- [ ] napi_throw_range_error
- [ ] napi_is_error
- [ ] napi_create_error
- [ ] napi_create_type_error
- [ ] napi_create_range_error
- [ ] napi_get_and_clear_last_exception
- [ ] napi_is_exception_pending
- [ ] napi_fatal_exception

### Fatal Errors

- [ ] napi_fatal_error

## Object Lifetime management

### Making handle lifespan shorter than that of the native method

- [ ] napi_open_handle_scope
- [ ] napi_close_handle_scope
- [ ] napi_open_escapable_handle_scope
- [ ] napi_close_escapable_handle_scope
- [ ] napi_escape_handle

### References to objects with a lifespan longer than that of the native method

- [ ] napi_create_reference
- [ ] napi_delete_reference
- [ ] napi_reference_ref
- [ ] napi_reference_unref
- [ ] napi_get_reference_value

### Cleanup on exit of the current Node.js instance

- [ ] napi_add_env_cleanup_hook
- [ ] napi_remove_env_cleanup_hook

## Module registration

## Working with JavaScript Values

### Enum types

- [ ] napi_valuetype
- [ ] napi_typedarray_type

### Object Creation Functions

- [ ] napi_create_array
- [ ] napi_create_array_with_length
- [ ] napi_create_arraybuffer
- [ ] napi_create_buffer
- [ ] napi_create_buffer_copy
- [ ] napi_create_external
- [ ] napi_create_external_arraybuffer
- [ ] napi_create_external_buffer
- [ ] napi_create_object
- [ ] napi_create_symbol
- [ ] napi_create_typedarray
- [ ] napi_create_dataview

### Functions to convert from C types to N-API

- [ ] napi_create_int32
- [ ] napi_create_uint32
- [ ] napi_create_int64
- [ ] napi_create_double
- [ ] napi_create_bigint_int64
- [ ] napi_create_bigint_uint64
- [ ] napi_create_bigint_words
- [ ] napi_create_string_latin1
- [ ] napi_create_string_utf16
- [ ] napi_create_string_utf8

### Functions to convert from N-API to C types

- [ ] napi_get_array_length
- [ ] napi_get_arraybuffer_info
- [ ] napi_get_buffer_info
- [ ] napi_get_prototype
- [ ] napi_get_typedarray_info
- [ ] napi_get_dataview_info
- [ ] napi_get_value_bool
- [ ] napi_get_value_double
- [ ] napi_get_value_bigint_int64
- [ ] napi_get_value_bigint_uint64
- [ ] napi_get_value_bigint_words
- [ ] napi_get_value_external
- [ ] napi_get_value_int32
- [ ] napi_get_value_int64
- [ ] napi_get_value_string_latin1
- [ ] napi_get_value_string_utf8
- [ ] napi_get_value_string_utf16
- [ ] napi_get_value_uint32

### Functions to get global instances

- [ ] napi_get_boolean
- [ ] napi_get_global
- [ ] napi_get_null
- [ ] napi_get_undefined

## Working with JavaScript Values - Abstract Operations

- [ ] napi_coerce_to_bool
- [ ] napi_coerce_to_number
- [ ] napi_coerce_to_object
- [ ] napi_coerce_to_string
- [ ] napi_typeof
- [ ] napi_instanceof
- [ ] napi_is_array
- [ ] napi_is_arraybuffer
- [ ] napi_is_buffer
- [ ] napi_is_error
- [ ] napi_is_typedarray
- [ ] napi_is_dataview
- [ ] napi_strict_equals

## Working with JavaScript Properties

### Structures

- [ ] napi_property_attributes
- [ ] napi_property_descriptor

### Functions

- [ ] napi_get_property_names
- [ ] napi_set_property
- [ ] napi_get_property
- [ ] napi_has_property
- [ ] napi_delete_property
- [ ] napi_has_own_property
- [ ] napi_set_named_property
- [ ] napi_get_named_property
- [ ] napi_has_named_property
- [ ] napi_set_element
- [ ] napi_get_element
- [ ] napi_has_element
- [ ] napi_delete_element
- [ ] napi_define_properties

# Working with JavaScript Functions

- [ ] napi_call_function
- [ ] napi_create_function
- [ ] napi_get_cb_info
- [ ] napi_get_new_target
- [ ] napi_new_instance

## Object Wrap

- [ ] napi_define_class
- [ ] napi_wrap
- [ ] napi_unwrap
- [ ] napi_remove_wrap

## Version Management

- [ ] napi_get_node_version
- [ ] napi_get_version

**Comment by yorkie** [comment]
Nice track jobs @legendecas!

**Comment by yorkie** [comment]
All stage 1 features have been implemented! Thank you @legendecas :)
