### ISSUE TITLE
Roadmap: v0.8.0

### ISSUE THREAD

**Issue by yorkie** [Rokid/ShadowNode#50]
### Supported Platform
- [x] Raspberry Pi
- [x] RokidOS

### Performance
- [ ] <s>buffer: optimize up the serialization performance over 20%</s>
- [x] use shared library to cost down the process shared RSS

### Development Experience:
- [x] collect the stack (execution offset) and generates the stack trace offline
  - [x] syntax
  - [x] otherwise
- [x] <s>redesign the iotjscode to fit with ShadowNode</s>

### API
- [x] install public headers in build script
- [ ] <s>support 80% N-API to write a native module</s>
- [x] add WebSocket client implementation, keep consistent with [WebSocket-Node](https://github.com/theturtle32/WebSocket-Node)
- [x] add console.time() and console.timeEnd() by @legendecas

**Comment by yorkie** [comment]
> Note that every `versioning` must own the following parts: 1) Supported Platform 2) Performance 3) Development Experience 4) API.> Note that every `versioning` must own the following parts: 1) Supported Platform 2) Performance 3) Development Experience 4) API.

**Comment by yorkie** [comment]
NAPI costs most works, let's move this task into next plan :)

**Comment by yorkie** [comment]
All required tasks are finished at 34ec49d2d4db810446f572f4ca836935ffb27503, let's close this.
